
// This file is generated by generate.ts
// These accounts are only for test.
// You should NEVER expose your mnemonic, secretKey/privateKey to anyone.
export type Account = {
  mnemonic: string;
  address: string;
  secretKey: string;
  publicKey: string;
}

export const tom = {
  "mnemonic": "helmet fault leave head protect face boat load asthma eyebrow clog cigar",
  "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdhzmt3yl9cgy5g77s6gts2fwtgxyjzuwc3utu92",
  "secretKey": "0x0b3387f0c6ddca131e7d0f5f501d72c41d0de897e3b87d0eea41422ee0a7c2fe",
  "publicKey": "0x0333046a47e2ec67853d56c6b5a3b4999f228a80c38992487d6568b131f268e1c1"
};

export const bob = {
  "mnemonic": "flash wink police royal hard story excuse genius reflect myself mammal way",
  "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqttulmgezra03krrytvp2lnsg5sj335a2gmqj0h0",
  "secretKey": "0x4303bc9949259f14d90da602aa4eb6290b22d887e79545026f67d5f3325046c6",
  "publicKey": "0x0261897ef04b8decb031cc9b2c1666adee0653ec5cdc60c7134e9a49c3e94494d7"
};

export const may = {
  "mnemonic": "merit plate various reason organ ladder speak harsh monster repeat clinic valve",
  "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtl3ng058vhq6zrnectwckeuymhshfn40s44dund",
  "secretKey": "0xa00637484a3c9d46b810d62da0bb63c18d90cbd5bba2ed4b212313ea9b5f72ce",
  "publicKey": "0x0371a0088d600a2bd9d7c0758df8aa8a965a771510da87a604dd709384333ae2ae"
};
