
// This file is generated by generate_accounts.ts  
export type Account = {
  mnemonic: string;
  address: string;
  secretKey: string;
  publicKey: string;
}

export const tom = {
  "mnemonic": "repair despair winter grid much ankle double render tone nominee mirror celery",
  "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2ssh0m0n9f2w0qreggc9cnpv5azh8rdyq53q4lq",
  "secretKey": "0xce1136cf7fefb53625780e69ba56cfbae8ba37cd13887c41915e0ae8a7022fff",
  "publicKey": "0x02a133f0f3e16e1068edef40e12440b86c9e3aaf6aba80007d445085e63bb92ccc"
};

export const bob = {
  "mnemonic": "speed quote viable absurd issue group future deal shrimp auto noodle dune",
  "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdn6k7pvph3vutq840d67d2pqr2mtn8pdc8zj3m2",
  "secretKey": "0xf4786b6bbfe2f95580d88a2dbf4ea5f48e2acc995fb90b39eb6ca5fa31c85de9",
  "publicKey": "0x0345d85491733cb95f2a9aeed8de5afa684940beecb101d35e31e77d1c1a640e08"
};

export const may = {
  "mnemonic": "vague afraid lens crash fatigue ranch cause fork never amateur oxygen wing",
  "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtkl0a2sndcytv6zgkmhhhya2r4ac9jkxs9av479",
  "secretKey": "0x238dacace46c2b55cddfe1f1216cd8b8e4b38af5b77b75bbc1aa08869f3857dc",
  "publicKey": "0x032cad2308e49cc3bff677a310f94be74d06129a07ffd5c90f882ff468314270d3"
};
