// This file is generated by omnilock.ts
import { Script } from '@ckb-lumos/lumos';
export const TYPE_ID_SCRIPT = {
  "codeHash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
  "hashType": "type",
  "args": "0xffaf6131766642186b2f71b64ed876ca61430b6e545fa183a65d79efafbe4550"
} as Script;

export const MAX_SUPPLY = 10000;

export const CURRENT_SUPPLY = 6000;

export const XUDT_SCRIPT = {
  "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
  "hashType": "type",
  "args": "0xf84e04d589cffc9023e39aece45d968d557d44f916201577c3a4ebf470d4fc97"
} as Script;

export const XUDT_SCRIPT_HASH = "0xd8ba4099ca8d5f3d613184d226727ec0b96fa14a540683fee8f9b9dc68c8f114";

export const OMNILOCK_SCRIPT = {
  "codeHash": "0xf329effd1c475a2978453c8600e1eaf0bc2087ee093c3ee64cc96ec6847752cb",
  "hashType": "type",
  "args": "0x005085dfb7cca9539e01e508c17130b29d15ce369008039fed33a642bd38a0ab4995b7eb31951d2beb667d56b863ea50f22d17e6aacd"
} as Script;

export const OMNILOCK_SCRIPT_HASH = "0xdd5b7af7a9d0f3fa0b7113305cf9ee777c161a370978c52d2eea9f39ada2aa8c";

export const OMNILOCK_TRANSACTION = {
  "version": "0x0",
  "cellDeps": [
    {
      "outPoint": {
        "txHash": "0xbf6fb538763efec2a70a6a3dcb7242787087e1030c4e7d86585bc63a9d337f5f",
        "index": "0x0"
      },
      "depType": "code"
    },
    {
      "outPoint": {
        "txHash": "0xec18bf0d857c981c3d1f4e17999b9b90c484b303378e94de1a57b0872f5d4602",
        "index": "0x0"
      },
      "depType": "code"
    },
    {
      "outPoint": {
        "txHash": "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
        "index": "0x0"
      },
      "depType": "depGroup"
    }
  ],
  "headerDeps": [],
  "inputs": [
    {
      "since": "0x0",
      "previousOutput": {
        "txHash": "0xa48eae2e7bcac4e42579d58590a4b5bec53a4f560d66e7d631d4f7cd571a33ac",
        "index": "0x0"
      }
    }
  ],
  "outputs": [
    {
      "capacity": "0xd91d54c48a",
      "lock": {
        "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
        "hashType": "type",
        "args": "0x5085dfb7cca9539e01e508c17130b29d15ce3690"
      }
    },
    {
      "capacity": "0x53d1ac100",
      "lock": {
        "codeHash": "0xf329effd1c475a2978453c8600e1eaf0bc2087ee093c3ee64cc96ec6847752cb",
        "hashType": "type",
        "args": "0x005085dfb7cca9539e01e508c17130b29d15ce369008039fed33a642bd38a0ab4995b7eb31951d2beb667d56b863ea50f22d17e6aacd"
      },
      "type": {
        "codeHash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
        "hashType": "type",
        "args": "0xffaf6131766642186b2f71b64ed876ca61430b6e545fa183a65d79efafbe4550"
      }
    }
  ],
  "outputsData": [
    "0x",
    "0x000000000000000000000000000000000010270000000000000000000000000000d8ba4099ca8d5f3d613184d226727ec0b96fa14a540683fee8f9b9dc68c8f114"
  ],
  "witnesses": [
    "0x5500000010000000550000005500000041000000bd66fe43a46ecb7f0e3d24e02be1405ccb8c11a6be01deedeb845bebdfc67dcd5e939ca9305a881a78c827027a7220e21d6b04e29c8227cdeb2024238adb96e101"
  ],
  "hash": "0x5adca92ad0c2d32849feb5a3cdbf01162ceeea54e28a0c9df9e47bb178448fb0"
};
